version: '3.8'

services:
  # Centralized Health Checker Service
  health-checker:
    build: .
    container_name: fastcache-health-checker
    hostname: fastcache-health-checker
    ports:
      - "8080:8080"
    environment:
      - HEALTH_CHECK_INTERVAL=30s
      - HEALTH_CHECK_TIMEOUT=5s
      - NODE_COUNT=3
    volumes:
      - fastcache_health_logs:/app/logs
    networks:
      - fastcache_network
    command: ["java", "-jar", "health-checker/build/libs/health-checker-1.0.0-fat.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # HAProxy Load Balancer
  load-balancer:
    image: haproxy:2.8
    container_name: fastcache-load-balancer
    hostname: fastcache-load-balancer
    ports:
      - "6380:6380"
      - "8404:8404"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - fastcache_network
    depends_on:
      - fastcache-proxy1
      - fastcache-proxy2
      - fastcache-proxy3
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6380"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # FastCache Proxies
  fastcache-proxy1:
    build: .
    container_name: fastcache-proxy1
    hostname: fastcache-proxy1
    ports:
      - "6382:6379"
    environment:
      - PROXY_ID=proxy1
      - PROXY_MODE=true
      - HEALTH_SERVICE_URL=http://health-checker:8080
      - CLUSTER_NODES=fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379
    volumes:
      - fastcache_proxy1_logs:/app/logs
    networks:
      - fastcache_network
    command: ["java", "-cp", "build/libs/FastCache-1.0.0-fat.jar", "com.fastcache.proxy.FastCacheProxy", "--host", "0.0.0.0", "--port", "6379", "--proxy-id", "proxy1", "--health-service", "http://health-checker:8080", "--cluster-nodes", "fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6379"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - health-checker

  fastcache-proxy2:
    build: .
    container_name: fastcache-proxy2
    hostname: fastcache-proxy2
    ports:
      - "6383:6379"
    environment:
      - PROXY_ID=proxy2
      - PROXY_MODE=true
      - HEALTH_SERVICE_URL=http://health-checker:8080
      - CLUSTER_NODES=fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379
    volumes:
      - fastcache_proxy2_logs:/app/logs
    networks:
      - fastcache_network
    command: ["java", "-cp", "build/libs/FastCache-1.0.0-fat.jar", "com.fastcache.proxy.FastCacheProxy", "--host", "0.0.0.0", "--port", "6379", "--proxy-id", "proxy2", "--health-service", "http://health-checker:8080", "--cluster-nodes", "fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6379"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - health-checker

  fastcache-proxy3:
    build: .
    container_name: fastcache-proxy3
    hostname: fastcache-proxy3
    ports:
      - "6384:6379"
    environment:
      - PROXY_ID=proxy3
      - PROXY_MODE=true
      - HEALTH_SERVICE_URL=http://health-checker:8080
      - CLUSTER_NODES=fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379
    volumes:
      - fastcache_proxy3_logs:/app/logs
    networks:
      - fastcache_network
    command: ["java", "-cp", "build/libs/FastCache-1.0.0-fat.jar", "com.fastcache.proxy.FastCacheProxy", "--host", "0.0.0.0", "--port", "6379", "--proxy-id", "proxy3", "--health-service", "http://health-checker:8080", "--cluster-nodes", "fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6379"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - health-checker

  # FastCache Data Nodes (1-3)
  fastcache-node1:
    build: .
    container_name: fastcache-node1
    hostname: fastcache-node1
    ports:
      - "7001:6379"
    environment:
      - NODE_ID=node1
      - NODE_HOST=fastcache-node1
      - NODE_PORT=6379
      - CLUSTER_MODE=true
      - PERSISTENCE_ENABLED=true
      - CLUSTER_NODES=fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379
    volumes:
      - fastcache_data1:/app/data
      - fastcache_logs1:/app/logs
    networks:
      - fastcache_network
    command: ["java", "-jar", "build/libs/FastCache-1.0.0-fat.jar", "--host", "0.0.0.0", "--port", "6379", "--node-id", "node1", "--cluster-mode", "--persistence-enabled", "--cluster-nodes", "fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6379"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  fastcache-node2:
    build: .
    container_name: fastcache-node2
    hostname: fastcache-node2
    ports:
      - "7002:6379"
    environment:
      - NODE_ID=node2
      - NODE_HOST=fastcache-node2
      - NODE_PORT=6379
      - CLUSTER_MODE=true
      - PERSISTENCE_ENABLED=true
      - CLUSTER_NODES=fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379
    volumes:
      - fastcache_data2:/app/data
      - fastcache_logs2:/app/logs
    networks:
      - fastcache_network
    command: ["java", "-jar", "build/libs/FastCache-1.0.0-fat.jar", "--host", "0.0.0.0", "--port", "6379", "--node-id", "node2", "--cluster-mode", "--persistence-enabled", "--cluster-nodes", "fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6379"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - fastcache-node1

  fastcache-node3:
    build: .
    container_name: fastcache-node3
    hostname: fastcache-node3
    ports:
      - "7003:6379"
    environment:
      - NODE_ID=node3
      - NODE_HOST=fastcache-node3
      - NODE_PORT=6379
      - CLUSTER_MODE=true
      - PERSISTENCE_ENABLED=true
      - CLUSTER_NODES=fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379
    volumes:
      - fastcache_data3:/app/data
      - fastcache_logs3:/app/logs
    networks:
      - fastcache_network
    command: ["java", "-jar", "build/libs/FastCache-1.0.0-fat.jar", "--host", "0.0.0.0", "--port", "6379", "--node-id", "node3", "--cluster-mode", "--persistence-enabled", "--cluster-nodes", "fastcache-node1:6379,fastcache-node2:6379,fastcache-node3:6379"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6379"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - fastcache-node1
      - fastcache-node2

networks:
  fastcache_network:
    driver: bridge

volumes:
  fastcache_health_logs:
  fastcache_proxy1_logs:
  fastcache_proxy2_logs:
  fastcache_proxy3_logs:
  fastcache_data1:
  fastcache_data2:
  fastcache_data3:
  fastcache_logs1:
  fastcache_logs2:
  fastcache_logs3: 